apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medquizai-data-pvc
  namespace: medquizai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2    # AWS EBS gp2
  resources:
    requests:
      storage: 10Gi
